name: Run Gradle on PRs
on: [pull_request, workflow_dispatch]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build
    - name: Check dirs
      run: ls -al; cd .gradle; ls -al; cd ../app/; ls -al; cd build; ls -al;